ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - maplibre-gl
  - unrs-resolver
  - vue-demi

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  node-forge@<1.3.2: '>=1.3.2'
  tar@=7.5.1: '>=7.5.2'
  unimport: 4.1.1
